#include "Pages.hpp"
#include <string>

std::string render_success_page(const std::string& username, int client_id, const std::string& log_content) {
    return
        "HTTP/1.1 200 OK\r\n"
        "Content-Type: text/html; charset=UTF-8\r\n"
        "Cache-Control: no-cache, no-store, must-revalidate\r\n"
        "Pragma: no-cache\r\n"
        "Expires: 0\r\n\r\n"
        "<!DOCTYPE html>"
        "<html lang=\"en\">"
        "<head>"
        "    <meta charset=\"UTF-8\">"
        "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
        "    <title>Matt Daemon - Dashboard</title>"
        "    <style>"
        "        * { margin: 0; padding: 0; box-sizing: border-box; }"
        "        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); min-height: 100vh; color: #333; }"
        "        .container { max-width: 1200px; margin: 0 auto; padding: 20px; }"
        "        .header { background: rgba(255, 255, 255, 0.95); border-radius: 15px; padding: 30px; margin-bottom: 30px; box-shadow: 0 8px 32px rgba(0, 0, 0, 0.1); backdrop-filter: blur(10px); text-align: center; }"
        "        .header h1 { color: #2c3e50; margin-bottom: 10px; font-size: 2.5em; font-weight: 300; }"
        "        .welcome-msg { color: #27ae60; font-size: 1.2em; font-weight: 500; }"
        "        .status-indicator { display: inline-block; width: 12px; height: 12px; background: #27ae60; border-radius: 50%; margin-right: 8px; animation: pulse 2s infinite; }"
        "        @keyframes pulse { 0% { opacity: 1; } 50% { opacity: 0.5; } 100% { opacity: 1; } }"
        "        .log-section { background: rgba(255, 255, 255, 0.95); border-radius: 15px; padding: 30px; box-shadow: 0 8px 32px rgba(0, 0, 0, 0.1); backdrop-filter: blur(10px); }"
        "        .log-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px; padding-bottom: 15px; border-bottom: 2px solid #ecf0f1; }"
        "        .log-title { color: #2c3e50; font-size: 1.5em; font-weight: 600; }"
        "        .refresh-info { color: #7f8c8d; font-size: 0.9em; display: flex; align-items: center; }"
        "        .log-container { background: #2c3e50; color: #ecf0f1; border-radius: 10px; padding: 20px; font-family: 'Courier New', monospace; font-size: 14px; line-height: 1.4; max-height: 500px; overflow-y: auto; white-space: pre-wrap; word-wrap: break-word; }"
        "        .log-container::-webkit-scrollbar { width: 8px; }"
        "        .log-container::-webkit-scrollbar-track { background: #34495e; border-radius: 4px; }"
        "        .log-container::-webkit-scrollbar-thumb { background: #7f8c8d; border-radius: 4px; }"
        "        .log-container::-webkit-scrollbar-thumb:hover { background: #95a5a6; }"
        "        .loading { text-align: center; color: #7f8c8d; font-style: italic; }"
        "        .footer { text-align: center; margin-top: 30px; color: rgba(255, 255, 255, 0.8); font-size: 0.9em; }"
        "        .info-cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 20px; margin-bottom: 30px; }"
        "        .info-card { background: rgba(255, 255, 255, 0.9); border-radius: 10px; padding: 20px; text-align: center; box-shadow: 0 4px 16px rgba(0, 0, 0, 0.1); }"
        "        .info-card h3 { color: #2c3e50; margin-bottom: 10px; }"
        "        .info-card p { color: #7f8c8d; font-size: 0.9em; }"
        "    </style>"
        "</head>"
        "<body>"
        "    <div class=\"container\">"
        "        <div class=\"header\">"
        "            <h1>Matt Daemon Dashboard</h1>"
        "            <p class=\"welcome-msg\">"
        "                <span class=\"status-indicator\"></span>"
        "                Welcome back, " + username + ""
        "            </p>"
        "        </div>"
        "        <div class=\"info-cards\">"
        "            <div class=\"info-card\"><h3>System Status</h3><p>Monitoring Active</p></div>"
        "            <div class=\"info-card\"><h3>Connection</h3><p>Client #" + std::to_string(client_id) + "</p></div>"
        "            <div class=\"info-card\"><h3>Auto Refresh</h3><p>Every 5 seconds</p></div>"
        "        </div>"
        "        <div class=\"log-section\">"
        "            <div class=\"log-header\">"
        "                <h2 class=\"log-title\">Recent Activity</h2>"
        "                <div class=\"refresh-info\"><span>🔄 Auto-refreshing...</span></div>"
        "            </div>"
        "            <div class=\"log-container\" id=\"logContent\">" + log_content + "</div>"
        "        </div>"
        "        <div class=\"footer\"><p>Matt Daemon Monitor • Last updated: <span id=\"timestamp\"></span></p></div>"
        "    </div>"
        "    <script>"
        "        function updateTimestamp() { document.getElementById('timestamp').textContent = new Date().toLocaleString(); }"
        "        updateTimestamp();"
        "        let refreshInterval;"
        "        function startAutoRefresh() { refreshInterval = setInterval(function() { updateTimestamp(); location.reload(); }, 5000); }"
        "        startAutoRefresh();"
        "        let scrollTimeout; const logContainer = document.getElementById('logContent');"
        "        logContainer.addEventListener('scroll', function() { clearInterval(refreshInterval); clearTimeout(scrollTimeout); scrollTimeout = setTimeout(function() { startAutoRefresh(); }, 10000); });"
        "        window.addEventListener('load', function() { logContainer.scrollTop = logContainer.scrollHeight; });"
        "    </script>"
        "</body></html>";
}

std::string render_failure_page() {
    return
        "HTTP/1.1 403 Forbidden\r\n"
        "Content-Type: text/html; charset=UTF-8\r\n"
        "Cache-Control: no-cache, no-store, must-revalidate\r\n\r\n"
        "<!DOCTYPE html>"
        "<html lang=\"en\">"
        "<head>"
        "    <meta charset=\"UTF-8\">"
        "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
        "    <title>Access Denied - Matt Daemon</title>"
        "    <style>"
        "        * { margin: 0; padding: 0; box-sizing: border-box; }"
        "        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background: linear-gradient(135deg, #e74c3c 0%, #c0392b 100%); min-height: 100vh; display: flex; align-items: center; justify-content: center; color: white; }"
        "        .error-container { background: rgba(255, 255, 255, 0.1); border-radius: 20px; padding: 40px; text-align: center; box-shadow: 0 8px 32px rgba(0, 0, 0, 0.3); backdrop-filter: blur(10px); border: 1px solid rgba(255, 255, 255, 0.2); max-width: 500px; width: 90%; }"
        "        .error-icon { font-size: 4em; margin-bottom: 20px; opacity: 0.8; }"
        "        .error-title { font-size: 2.5em; font-weight: 300; margin-bottom: 15px; }"
        "        .error-message { font-size: 1.2em; margin-bottom: 30px; opacity: 0.9; line-height: 1.5; }"
        "        .error-details { background: rgba(0, 0, 0, 0.2); border-radius: 10px; padding: 20px; margin-bottom: 30px; font-family: 'Courier New', monospace; font-size: 0.9em; }"
        "        .retry-info { opacity: 0.7; font-size: 0.9em; }"
        "        .pulse { animation: pulse 2s infinite; }"
        "        @keyframes pulse { 0% { transform: scale(1); } 50% { transform: scale(1.05); } 100% { transform: scale(1); } }"
        "    </style>"
        "</head>"
        "<body>"
        "    <div class=\"error-container\">"
        "        <div class=\"error-icon pulse\">🔒</div>"
        "        <h1 class=\"error-title\">Access Denied</h1>"
        "        <p class=\"error-message\">Authentication failed. Invalid credentials provided.</p>"
        "        <div class=\"error-details\">"
        "            <strong>Error Code:</strong> 403 Forbidden<br>"
        "            <strong>Service:</strong> Matt Daemon Monitor<br>"
        "            <strong>Time:</strong> <span id=\"errorTime\"></span>"
        "        </div>"
        "        <p class=\"retry-info\">Please check your username and password and try again.</p>"
        "    </div>"
        "    <script>document.getElementById('errorTime').textContent = new Date().toLocaleString();</script>"
        "</body></html>";
}
