#include "web_interface.hpp"

// Use a fixed string instead of external variable for now
const std::string WEB_AUTH_FILE = "./matt_daemon_auth.txt";

std::string WebInterface::get_common_styles() {
    return 
        "body { font-family: Arial, sans-serif; margin: 0; padding: 0; }\n"
        ".container { max-width: 800px; margin: 0 auto; background: white; padding: 30px; border-radius: 10px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }\n"
        ".btn-primary { background-color: #007bff; color: white; border: none; padding: 10px 20px; border-radius: 3px; cursor: pointer; margin: 5px; }\n"
        ".btn-primary:hover { background-color: #0056b3; }\n"
        ".btn-success { background-color: #28a745; }\n"
        ".btn-success:hover { background-color: #1e7e34; }\n"
        ".error { background-color: #f8d7da; color: #721c24; padding: 10px; border-radius: 5px; margin-top: 15px; display: none; }\n"
        ".info { background-color: #d1ecf1; color: #0c5460; padding: 15px; border-radius: 5px; margin: 20px 0; }\n";
}

std::string WebInterface::get_login_styles() {
    return get_common_styles() +
        "body { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); height: 100vh; display: flex; justify-content: center; align-items: center; }\n"
        ".login-container { background: white; padding: 40px; border-radius: 15px; box-shadow: 0 10px 30px rgba(0,0,0,0.3); width: 400px; text-align: center; }\n"
        ".logo { font-size: 2.5em; margin-bottom: 20px; color: #333; }\n"
        "h1 { color: #333; margin-bottom: 10px; }\n"
        ".subtitle { color: #666; margin-bottom: 30px; font-size: 14px; }\n"
        ".privilege-warning { background-color: #fff3cd; color: #856404; padding: 15px; border-radius: 5px; margin-bottom: 20px; border: 1px solid #ffeaa7; }\n"
        ".form-group { margin-bottom: 20px; text-align: left; }\n"
        "label { display: block; margin-bottom: 5px; color: #333; font-weight: bold; }\n"
        "input[type=password] { width: 100%; padding: 12px; border: 2px solid #ddd; border-radius: 5px; font-size: 16px; box-sizing: border-box; }\n"
        "input[type=password]:focus { border-color: #667eea; outline: none; }\n"
        ".login-btn { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 12px 30px; border: none; border-radius: 5px; font-size: 16px; cursor: pointer; width: 100%; }\n"
        ".login-btn:hover { opacity: 0.9; }\n";
}

std::string WebInterface::get_dashboard_styles() {
    return get_common_styles() +
        "body { margin: 40px; background-color: #f0f0f0; }\n"
        "h1 { color: #333; text-align: center; }\n"
        ".status { padding: 15px; margin: 20px 0; border-radius: 5px; text-align: center; font-weight: bold; }\n"
        ".running { background-color: #d4edda; color: #155724; border: 1px solid #c3e6cb; }\n"
        ".stopped { background-color: #f8d7da; color: #721c24; border: 1px solid #f5c6cb; }\n"
        "button { background-color: #dc3545; color: white; border: none; padding: 15px 30px; font-size: 16px; border-radius: 5px; cursor: pointer; display: block; margin: 20px auto; }\n"
        "button:hover { background-color: #c82333; }\n"
        "button:disabled { background-color: #6c757d; cursor: not-allowed; }\n"
        ".logs { background-color: #f8f9fa; padding: 15px; border-radius: 5px; margin: 20px 0; max-height: 300px; overflow-y: auto; font-family: monospace; white-space: pre-wrap; }\n"
        ".shell-section { margin: 30px 0; padding: 20px; background-color: #f8f9fa; border-radius: 5px; border: 1px solid #dee2e6; }\n"
        ".shell-input { width: 100%; padding: 10px; margin: 10px 0; border: 1px solid #ccc; border-radius: 3px; font-family: monospace; }\n"
        ".shell-output { background-color: #000; color: #0f0; padding: 15px; border-radius: 5px; max-height: 300px; overflow-y: auto; font-family: monospace; white-space: pre-wrap; }\n"
        ".tabs { display: flex; margin-bottom: 20px; }\n"
        ".tab { padding: 10px 20px; background-color: #e9ecef; border: 1px solid #dee2e6; cursor: pointer; margin-right: 5px; border-radius: 5px 5px 0 0; }\n"
        ".tab.active { background-color: #fff; border-bottom: 1px solid #fff; }\n"
        ".tab-content { display: none; }\n"
        ".tab-content.active { display: block; }\n";
}

std::string WebInterface::get_common_scripts() {
    return 
        "function switchTab(tabName) {\n"
        "    document.querySelectorAll('.tab-content').forEach(tab => tab.classList.remove('active'));\n"
        "    document.querySelectorAll('.tab').forEach(tab => tab.classList.remove('active'));\n"
        "    document.getElementById(tabName + '-tab').classList.add('active');\n"
        "    event.target.classList.add('active');\n"
        "}\n";
}

std::string WebInterface::get_dashboard_scripts() {
    return get_common_scripts() +
        "function stopDaemon() {\n"
        "    const button = document.querySelector('button');\n"
        "    button.disabled = true;\n"
        "    button.textContent = 'Stopping...';\n"
        "    \n"
        "    fetch('/stop', { method: 'POST' })\n"
        "    .then(response => response.text())\n"
        "    .then(data => {\n"
        "        document.getElementById('message').innerHTML = '<div class=\"info\">Daemon stop signal sent. The daemon is shutting down...</div>';\n"
        "        setTimeout(() => {\n"
        "            document.querySelector('.status').className = 'status stopped';\n"
        "            document.querySelector('.status').innerHTML = '🔴 Daemon Stopped';\n"
        "            button.textContent = 'Daemon Stopped';\n"
        "        }, 1000);\n"
        "    })\n"
        "    .catch(error => {\n"
        "        document.getElementById('message').innerHTML = '<div class=\"info\">Error: ' + error + '</div>';\n"
        "        button.disabled = false;\n"
        "        button.textContent = 'Stop Daemon';\n"
        "    });\n"
        "}\n"
        "\n"
        "function loadLogs() {\n"
        "    fetch('/logs', { method: 'GET' })\n"
        "    .then(response => response.text())\n"
        "    .then(data => {\n"
        "        document.getElementById('logs').textContent = data;\n"
        "        document.getElementById('logs').scrollTop = document.getElementById('logs').scrollHeight;\n"
        "    })\n"
        "    .catch(error => {\n"
        "        document.getElementById('logs').textContent = 'Error loading logs: ' + error;\n"
        "    });\n"
        "}\n"
        "\n"
        "function downloadLogs() {\n"
        "    fetch('/logs')\n"
        "    .then(response => response.text())\n"
        "    .then(data => {\n"
        "        const blob = new Blob([data], { type: 'text/plain' });\n"
        "        const url = window.URL.createObjectURL(blob);\n"
        "        const a = document.createElement('a');\n"
        "        a.href = url;\n"
        "        a.download = 'matt_daemon_logs_' + new Date().toISOString().slice(0,19).replace(/:/g, '-') + '.txt';\n"
        "        a.click();\n"
        "        window.URL.revokeObjectURL(url);\n"
        "    });\n"
        "}\n"
        "\n"
        "function executeShellCommand() {\n"
        "    const command = document.getElementById('shellInput').value;\n"
        "    if (!command.trim()) return;\n"
        "    \n"
        "    const output = document.getElementById('shellOutput');\n"
        "    output.textContent += '$ ' + command + '\\n';\n"
        "    \n"
        "    fetch('/shell', {\n"
        "        method: 'POST',\n"
        "        headers: { 'Content-Type': 'application/json' },\n"
        "        body: JSON.stringify({ command: command })\n"
        "    })\n"
        "    .then(response => response.text())\n"
        "    .then(data => {\n"
        "        output.textContent += data + '\\n\\n';\n"
        "        output.scrollTop = output.scrollHeight;\n"
        "        document.getElementById('shellInput').value = '';\n"
        "    })\n"
        "    .catch(error => {\n"
        "        output.textContent += 'Error: ' + error + '\\n\\n';\n"
        "    });\n"
        "}\n"
        "\n"
        "function handleShellEnter(event) {\n"
        "    if (event.key === 'Enter') {\n"
        "        executeShellCommand();\n"
        "    }\n"
        "}\n"
        "\n"
        "function clearShellOutput() {\n"
        "    document.getElementById('shellOutput').textContent = 'Shell cleared.\\n\\n';\n"
        "}\n"
        "\n"
        "function archiveLogs() {\n"
        "    fetch('/archive', { method: 'POST' })\n"
        "    .then(response => response.text())\n"
        "    .then(data => {\n"
        "        document.getElementById('archiveOutput').textContent = data;\n"
        "    })\n"
        "    .catch(error => {\n"
        "        document.getElementById('archiveOutput').textContent = 'Error: ' + error;\n"
        "    });\n"
        "}\n"
        "\n"
        "function getLogStats() {\n"
        "    fetch('/stats', { method: 'GET' })\n"
        "    .then(response => response.text())\n"
        "    .then(data => {\n"
        "        document.getElementById('archiveOutput').textContent = data;\n"
        "    })\n"
        "    .catch(error => {\n"
        "        document.getElementById('archiveOutput').textContent = 'Error: ' + error;\n"
        "    });\n"
        "}\n"
        "\n"
        "function cleanOldLogs() {\n"
        "    if (confirm('Are you sure you want to clean old log entries? This action cannot be undone.')) {\n"
        "        fetch('/clean', { method: 'POST' })\n"
        "        .then(response => response.text())\n"
        "        .then(data => {\n"
        "            document.getElementById('archiveOutput').textContent = data;\n"
        "        })\n"
        "        .catch(error => {\n"
        "            document.getElementById('archiveOutput').textContent = 'Error: ' + error;\n"
        "        });\n"
        "    }\n"
        "}\n"
        "\n"
        "window.onload = function() {\n"
        "    loadLogs();\n"
        "    setInterval(loadLogs, 10000);\n"
        "}\n";
}

std::string WebInterface::get_login_page() {
    return "<!DOCTYPE html>\n"
        "<html>\n"
        "<head>\n"
        "    <title>Matt Daemon - Authentication Required</title>\n"
        "    <style>\n" + get_login_styles() + "</style>\n"
        "</head>\n"
        "<body>\n"
        "    <div class=\"login-container\">\n"
        "        <div class=\"logo\">🔒</div>\n"
        "        <h1>Matt Daemon</h1>\n"
        "        <div class=\"subtitle\">Authentication Required</div>\n"
        "        \n"
        "        <div class=\"privilege-warning\">\n"
        "            ⚠️ <strong>Root Access Required</strong><br>\n"
        "            This daemon requires administrator privileges to access.\n"
        "        </div>\n"
        "        \n"
        "        <div class=\"info\">\n"
        "            <strong>Authentication File:</strong> " + WEB_AUTH_FILE + "<br>\n"
        "            <strong>Status:</strong> Password protection active\n"
        "        </div>\n"
        "        \n"
        "        <form id=\"loginForm\">\n"
        "            <div class=\"form-group\">\n"
        "                <label for=\"password\">Administrator Password:</label>\n"
        "                <input type=\"password\" id=\"password\" name=\"password\" placeholder=\"Enter admin password\" required>\n"
        "            </div>\n"
        "            <button type=\"submit\" class=\"login-btn\">🔓 Access Daemon</button>\n"
        "        </form>\n"
        "        \n"
        "        <div id=\"error\" class=\"error\"></div>\n"
        "        \n"
        "        <script>\n"
        "            document.getElementById('loginForm').addEventListener('submit', function(e) {\n"
        "                e.preventDefault();\n"
        "                \n"
        "                const password = document.getElementById('password').value;\n"
        "                const errorDiv = document.getElementById('error');\n"
        "                \n"
        "                fetch('/auth', {\n"
        "                    method: 'POST',\n"
        "                    headers: { 'Content-Type': 'application/json' },\n"
        "                    body: JSON.stringify({ password: password })\n"
        "                })\n"
        "                .then(response => response.json())\n"
        "                .then(data => {\n"
        "                    if (data.success) {\n"
        "                        localStorage.setItem('matt_daemon_session', data.token);\n"
        "                        window.location.href = '/dashboard';\n"
        "                    } else {\n"
        "                        errorDiv.textContent = 'Invalid password. Access denied.';\n"
        "                        errorDiv.style.display = 'block';\n"
        "                        document.getElementById('password').value = '';\n"
        "                    }\n"
        "                })\n"
        "                .catch(error => {\n"
        "                    errorDiv.textContent = 'Authentication error: ' + error;\n"
        "                    errorDiv.style.display = 'block';\n"
        "                });\n"
        "            });\n"
        "        </script>\n"
        "    </div>\n"
        "</body>\n"
        "</html>";
}

std::string WebInterface::get_dashboard_page() {
    return "<!DOCTYPE html>\n"
        "<html>\n"
        "<head>\n"
        "    <title>Matt Daemon Controller</title>\n"
        "    <style>\n" + get_dashboard_styles() + "</style>\n"
        "</head>\n"
        "<body>\n"
        "    <div class=\"container\">\n"
        "        <h1>Matt Daemon Controller</h1>\n"
        "        <div class=\"status running\">\n"
        "            🟢 Daemon is Running\n"
        "        </div>\n"
        "        <div class=\"info\">\n"
        "            <strong>Daemon Information:</strong><br>\n"
        "            • Server running on port 8080<br>\n"
        "            • Web interface on port 8080<br>\n"
        "            • Lock file: /tmp/matt_daemon.lock<br>\n"
        "            • Log file: /tmp/matt_daemon.log\n"
        "        </div>\n"
        "        <button onclick=\"stopDaemon()\">Stop Daemon</button>\n"
        "        <div id=\"message\"></div>\n"
        "        \n"
        "        <div class=\"tabs\">\n"
        "            <div class=\"tab active\" onclick=\"switchTab('logs')\">📋 Logs</div>\n"
        "            <div class=\"tab\" onclick=\"switchTab('shell')\">💻 Remote Shell</div>\n"
        "            <div class=\"tab\" onclick=\"switchTab('archive')\">📦 Log Archive</div>\n"
        "        </div>\n"
        "        \n"
        "        <div id=\"logs-tab\" class=\"tab-content active\">\n"
        "            <div class=\"info\">\n"
        "                <strong>Daemon Logs (Last 50 lines):</strong>\n"
        "                <button class=\"btn-primary\" onclick=\"loadLogs()\">🔄 Refresh</button>\n"
        "                <button class=\"btn-success\" onclick=\"downloadLogs()\">💾 Download</button>\n"
        "            </div>\n"
        "            <div id=\"logs\" class=\"logs\">Click 'Refresh' to load logs...</div>\n"
        "        </div>\n"
        "        \n"
        "        <div id=\"shell-tab\" class=\"tab-content\">\n"
        "            <div class=\"shell-section\">\n"
        "                <h3>🔧 Remote Shell Interface</h3>\n"
        "                <p>Execute commands on the server (be careful!):</p>\n"
        "                <input type=\"text\" id=\"shellInput\" class=\"shell-input\" placeholder=\"Enter command (e.g., 'ls -la', 'ps aux', 'uptime')\" onkeypress=\"handleShellEnter(event)\">\n"
        "                <button class=\"btn-primary\" onclick=\"executeShellCommand()\">Execute</button>\n"
        "                <button class=\"btn-primary\" onclick=\"clearShellOutput()\">Clear</button>\n"
        "                <div id=\"shellOutput\" class=\"shell-output\">Welcome to Matt Daemon Remote Shell\\nType commands and press Execute or Enter\\n\\n</div>\n"
        "            </div>\n"
        "        </div>\n"
        "        \n"
        "        <div id=\"archive-tab\" class=\"tab-content\">\n"
        "            <div class=\"info\">\n"
        "                <h3>📦 Advanced Log Archival</h3>\n"
        "                <p>Manage and archive daemon logs:</p>\n"
        "                <button class=\"btn-primary\" onclick=\"archiveLogs()\">📦 Create Archive</button>\n"
        "                <button class=\"btn-primary\" onclick=\"getLogStats()\">📊 Get Statistics</button>\n"
        "                <button class=\"btn-success\" onclick=\"cleanOldLogs()\">🧹 Clean Old Logs</button>\n"
        "            </div>\n"
        "            <div id=\"archiveOutput\" class=\"logs\">Archive operations will appear here...</div>\n"
        "        </div>\n"
        "        \n"
        "        <script>\n" + get_dashboard_scripts() + "</script>\n"
        "    </div>\n"
        "</body>\n"
        "</html>";
}

std::string WebInterface::create_http_response(const std::string& content, const std::string& content_type) {
    std::string response = "HTTP/1.1 200 OK\r\n";
    response += "Content-Type: " + content_type + "\r\n";
    response += "Content-Length: " + std::to_string(content.length()) + "\r\n";
    response += "Connection: close\r\n\r\n";
    response += content;
    return response;
}

std::string WebInterface::create_json_response(const std::string& json_content) {
    return create_http_response(json_content, "application/json");
}

std::string WebInterface::create_redirect_response(const std::string& location) {
    std::string response = "HTTP/1.1 302 Found\r\n";
    response += "Location: " + location + "\r\n";
    response += "Connection: close\r\n\r\n";
    return response;
}
